version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-south-1)

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t 841042906610.dkr.ecr.ap-south-1.amazonaws.com/cd-image-repo:latest .
      - docker tag 841042906610.dkr.ecr.ap-south-1.amazonaws.com/cd-image-repo:latest 841042906610.dkr.ecr.ap-south-1.amazonaws.com/cd-image-repo:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 841042906610.dkr.ecr.ap-south-1.amazonaws.com/cd-image-repo:latest
      - docker push 841042906610.dkr.ecr.ap-south-1.amazonaws.com/cd-image-repo:$CODEBUILD_RESOLVED_SOURCE_VERSION

artifacts:
  files: docker-image.json

