version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "841042906610"
    AWS_REGION: "ap-south-1"
    REPO_NAME: "cd-image-repo"
    LAMBDA_FUNCTION_TO_DEPLOY: "TEST_LAMBDA"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws --region $AWS_REGION ecr get-login-password | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t new_docker_image .
      - docker tag new_docker_image:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:latest
      - echo Invoking the Image Update Lambda function...
      - aws lambda update-function-code --function-name TEST_LAMBDA --image-uri $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:latest
      - echo New image deployed on $LAMBDA_FUNCTION_TO_DEPLOY successfully...


name: Build and Deploy

on:
  push:
    branches:
      - csv-changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Get AWS Account ID
        id: aws-account-id
        run: |
          USER_ID_DEV=$(aws sts get-caller-identity --query "Account" --output text)
          echo "AWS_ACCOUNT_ID=$USER_ID_DEV" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          repo=mdm-scrubber
          branch=${GITHUB_REF#refs/heads/}
          image=${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com/$repo:$branch
          echo "dockerizing $branch to $image"
          docker build -t $image --platform linux/amd64 -f dockerize/dockerfile .

      - name: Login to Amazon ECR
        run: |
          echo "Logging into Amazon ECR"
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.ap-south-1.amazonaws.com

      - name: Push Docker image to ECR
        run: |
          echo "Pushing $image to Amazon ECR"
          docker push $image

      - name: Update Lambda function
        run: |
          lambdaname=mdm-scrubber-csv
          echo "Deploying on Lambda: $lambdaname"
          aws lambda update-function-code \
            --function-name $lambdaname \
            --image-uri $image
