version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "841042906610"
    AWS_REGION: "ap-south-1"
    REPO_NAME: "cd-image-repo"
    LAMBDA_FUNCTION_TO_DEPLOY: "TEST_LAMBDA"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws --region $AWS_REGION ecr get-login-password | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t new_docker_image .
      - docker tag new_docker_image:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:latest
      - echo Invoking the Image Update Lambda function...
      - aws lambda update-function-code \
        --function-name  TEST_LAMBDA \
        --image-uri $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:latest
      - echo New image deployed on $LAMBDA_FUNCTION_TO_DEPLOY successfully...
