FROM public.ecr.aws/lambda/python:3.9

ENV LIBREOFFICE_VERSION=7.6.2
ENV LIBREOFFICE_PATH=/opt/libreoffice${LIBREOFFICE_VERSION}

RUN yum install -y tar.x86_64 poppler-utils cairo cups libXinerama.x86_64 cups-libs dbus-glib gcc && \
    yum remove -y openoffice* libreoffice*

ENV PATH="${LIBREOFFICE_PATH}/program:${PATH}"

RUN yum remove -y openoffice* libreoffice* && \
    rm -rf ${LIBREOFFICE_PATH} && \
    yum
