name: CD Workflow

on:
  pull_request:
    branches:
      - main
    types: 
      - opened 
      - synchronize        

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Deploy 
        run: echo Proceeding with deployment
