name: Central Workflow

on:
  workflow_dispatch:
    inputs:
      repository-names:
        description: 'Repository Names (comma-separated)'
        required: true

jobs:
  check-pull-requests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check Pull Requests
      run: |
        repos="${{ github.event.inputs.repository-names }}"
        for repo in $repos; do
          echo repo_name = $repo
          echo "Checking PRs in $repo"
          pull_requests=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$repo/pulls?state=open")
          echo Pull requests : $pull_requests
          # for pr in $(echo $pull_requests | jq -r '.[] | @base64'); do
          #   approvals=$(echo $pr | base64 --decode | jq '.reviews[] | select(.state == "APPROVED") | .user.login')
          #   pr_number=$(echo $pr | base64 --decode | jq -r '.number')
          #   if [ "$(echo $approvals | wc -w)" -ge 2 ]; then
          #     echo "PR #$pr_number in $repo has 2 or more approvals."
          #     # Create a status check with success
          #     curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d '{"state": "success", "description": "2 approvals", "context": "approval-check"}' "https://api.github.com/repos/$repo/statuses/$GITHUB_SHA"
          #   else
          #     echo "PR #$pr_number in $repo does not have 2 approvals."
          #   fi
          # done
        done

