name: Check status
on:
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Signal from Manual Workflow
        run: |
          CHECK_NAME="manual-signal"
          STATUS=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status" | jq -r ".statuses[] | select(.context == \"$CHECK_NAME\") | .state")
      
          if [ "$STATUS" != "success" ]; then
            echo "Manual checks have not passed. Aborting the merge process."
            exit 1
          fi
