name: CI Workflow

on:
  pull_request:
    branches:
      - main
    types: 
      - opened 
      - synchronize        

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Build code
        run: echo Code image built successfully

      - name: Deploy to lambda
        run: echo Deployed to AWS Lambda successfully

  Testing:
    runs-on: ubuntu-latest
    needs: Build

    steps:
      - name: Run tests
        run: echo Running tests
