name: CI Workflow

on:
  pull_request:
    branches:
      - main
    types: 
      - opened 
      - synchronize        

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Build code
        run: echo Code image built successfully

      - name: Deploy to lambda
        run: echo Deployed to AWS Lambda successfully
  
  testing:
    runs-on: ubuntu-latest
    needs: build_and_deploy

    steps:
      - name: Initiate testing
      - run: echo Testing Lambda invoked successfully
      
