name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to deploy'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Branch Exists
        run: |
          BRANCH_NAME=${{ github.event.inputs.branch_name }}
          if git ls-remote --exit-code --heads origin "$BRANCH_NAME"; then
            echo "Branch $BRANCH_NAME exists."
          else
            echo "Branch $BRANCH_NAME does not exist."
            exit 1
          fi
        
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build and push Docker image
        run: |
          docker build -t dev-docker-image .
          docker tag dev-docker-image:latest ${{ steps.login-ecr.outputs.registry }}/cd-image-repo:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/cd-image-repo:latest

      - name: Update AWS Lambda function
        run: |
          aws lambda update-function-code \
            --function-name TEST_LAMBDA \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/cd-image-repo:latest
          
