name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to be deployed'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download and Verify LibreOffice
        run: |
          LIBREOFFICE_VERSION=7.6.2
          LIBREOFFICE_PATH=/opt/libreoffice${LIBREOFFICE_VERSION}
          LIBREOFFICE_TAR_URL=https://www.libreoffice.org/donate/dl/rpm-x86_64/${LIBREOFFICE_VERSION}/en-US/LibreOffice_${LIBREOFFICE_VERSION}_Linux_x86-64_rpm.tar.gz
          LIBREOFFICE_TAR_CHECKSUM=920d61dd9ee4263d0960fca8b14e95d36602c589720903120cfd0c2e41916462
      
          echo "Downloading file..."
          curl -L -o LibreOffice_${LIBREOFFICE_VERSION}_Linux_x86-64_rpm.tar.gz ${LIBREOFFICE_TAR_URL}
          ls -l LibreOffice_${LIBREOFFICE_VERSION}_Linux_x86-64_rpm.tar.gz  # Print file size
          file LibreOffice_${LIBREOFFICE_VERSION}_Linux_x86-64_rpm.tar.gz  # Identify file type
          echo "Verifying checksum..."
          echo "${LIBREOFFICE_TAR_CHECKSUM}  LibreOffice_${LIBREOFFICE_VERSION}_Linux_x86-64_rpm.tar.gz" | sha256sum -c -
        
      - name: Build and push Docker image
        run: |
          docker build -t dev-docker-image .
          docker tag dev-docker-image:latest ${{ steps.login-ecr.outputs.registry }}/cd-image-repo:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/cd-image-repo:latest

      - name: Update AWS Lambda function
        run: |
          aws lambda update-function-code \
            --function-name TEST_LAMBDA \
            --image-uri ${{ steps.login-ecr.outputs.registry }}/cd-image-repo:latest
