name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to be deployed'
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download LibreOffice from S3
        run: |
          aws s3 cp s3://#S3_BUCKET/$LIBREOFFICE_FILE .
        env: 
          S3_BUCKET: essential-downloads
          LIBREOFFICE_FILE: LibreOffice_7.3.4_Linux_x86-64_rpm.tar.gz

      - name: Decrypt JSON file
        run: |
          openssl aes-256-cbc -d -in confidential.json.enc -out confidential.json -k ${{ secrets.PASSPHRASE }} -pbkdf2

      - name: Display decrypted content
        run: cat confidential.json

#      - name: Build and push Docker image
#        run: |
#          docker build -t dev-docker-image .
#          docker tag dev-docker-image:latest ${{ steps.login-ecr.outputs.registry }}/cd-image-repo:latest
#          docker push ${{ steps.login-ecr.outputs.registry }}/cd-image-repo:latest
#
#      - name: Update AWS Lambda function
#        run: |
#          aws lambda update-function-code \
#            --function-name TEST_LAMBDA \
#            --image-uri ${{ steps.login-ecr.outputs.registry }}/cd-image-repo:latest
