name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to deploy'
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install and configure AWS CLI
        run: |
          pip install --upgrade awscli
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws configure set region ap-south-1
          aws configure set output json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_DEFAULT_REGION: ap-south-1
          AWS_DEFAULT_OUTPUT: json
        
      - name: Docker build and push
        run: |
          bash dockerize/docker_build_push.sh
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          AWS_DEFAULT_REGION: ap-south-1
          AWS_DEFAULT_OUTPUT: json
          
